---

server:
  port: 8762
  
eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
##Spring Cloud API Gateway for manual routing of requests
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      - id: security-microservice
        uri: lb://SECURITY-MICROSERVICE
        predicates:
          - Path=/infymemobile/security/** 
      
      - id: user-microservice
        uri: lb://USER-MICROSERVICE 
        predicates:
          - Path=/infymemobile/user/**
        filters:
          - name: JwtAuthenticationFilter
        
      - id: account-microservice
        uri: lb://ACCOUNT-MICROSERVICE 
        predicates:
          - Path=/infymemobile/account/** 
        filters:
          - name: JwtAuthenticationFilter
 

